### ISSUE TITLE
Hashing `AccountId` to avoid non-existent collisions

### ISSUE THREAD

**Issue by willemneal** [vecno-io/arc-near-contracts#1]
https://github.com/vecno-io/arc-near-contracts/blob/5c0c3b55622da61ceb688177b721d275120fa7f5/nft-contract/src/internal.rs#L41-42

Isn't an `AccountId` already guaranteed to be unique?

This is in the `near-sdk-rs`'s code too, but has always seemed odd to me.  You use extra space for every prefix and extra gas to do the hash.

**Comment by nodra-vr** [comment]
I agree, it feels odd. In the old AS contract, I removed the hash without issues, still working on the Rust implementation it was a last-minute switch to meet a hackathon deadline. For now, I have not found a reason why the id is hashed and I might remove it unless I run into trouble doing so. 

This setup seems to work just as well:
~~~
pub enum StorageKey {
    TokenPerOwnerInner { account_id: String },
}
~~~

Ref.
https://github.com/vecno-io/arc-near-contracts/blob/5c0c3b55622da61ceb688177b721d275120fa7f5/nft-contract/src/lib.rs#L58
https://github.com/vecno-io/arc-near-contracts/blob/5c0c3b55622da61ceb688177b721d275120fa7f5/nft-contract/src/internal.rs#L103

**Comment by nodra-vr** [comment]
@willemneal After doing some more reading and testing I can tell you the contract does break when removing the hash.

The fixed size on the storage key is required to avoid changes in the storage cost of the contract. For example, if `bob.near` send a token to `alice.near` and there were no reserve funds on the contract the transaction would fail.

**Comment by willemneal** [comment]
@koen-vr, you could still charge the full price and this would save on gas, but it's probably not worth it.

**Comment by nodra-vr** [comment]
@willemneal It would double the storage cost as an AccountID has a maximum size of 64 bytes, vs the 32bytes for the hash. With gas being cheap and storage rather expensive, It becomes hard to justify.

**Comment by willemneal** [comment]
Ah thought the has was also 64.  Definitely!
